baseURL: https://docs.velociraptor.app/
languageCode: en-us
title: "Velociraptor - Digging deeper!"

theme: "hugo-theme-learn"

params:
  themeVariant: "mine"
  disableSearch: true
  showVisitedLinks: false
  disableMermaid: true
  disableBreadcrumb: true
  disableNextPrev: true
  disableLandingPageButton: true
  custom_css:
    - css/atom-one-light.css
    - https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    noClasses: true
    style: pygments

menu:
  shortcuts:
   -  name: "<i class='fab fa-github'></i> Github repo"
      identifier: "ds"
      url: "https://github.com/Velocidex/velociraptor"
      weight: 10
   -  name: "<i class='fas fa-search'></i> Search"
      url: "search"
